apiVersion: v1
  kind: Service
  metadata:
    name: hello-human
    namespace: default   
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 8000
    selector:
      app: hello-human
    type: LoadBalancer
